name: FORM - Specification New Field Request
description: An issue form for submitting picklist new field requests
title: "NFR: [current term label]"
labels: ["field request"]
body:
  - type: input
    id: field-label
    attributes:
      label: Proposed Field Label
      description: 
      placeholder: ex. sequencing platform
    validations:
      required: true
  - type: textarea
    id: definition
    attributes: 
      label: Definition/Description
      description: Please provide brief description to help curators understand and differentiate your intended field.
      placeholder: ex. The platform technology used to perform the sequencing.
    validations:
      required: true
  - type: input
    id: definition-source
    attributes: 
      label: Definition Source
      description: Any sources that contributed to the definition/description provided (e.g. a URL, identifier, ORCiD).
      placeholder: ex. https://en.wikipedia.org/wiki/<relevant page>
    validations:
      required: false
  - type: textarea
    id: guidance
    attributes: 
      label: Guidance
      description: Additional information on how to use this field.
      placeholder: ex. Provide the name of the company that created the sequencing instrument by selecting a value from the template pick list. If the information is unknown or cannot be provided, leave blank or provide a null value.
    validations:
      required: false
  - type: input
    id: example
    attributes: 
      label: Example of Usage
      description: A example(s) of proposed field value(s).
      placeholder: ex. Illumina
    validations:
      required: false
  - type: input
    id: alternative-labels
    attributes: 
      label: Alternative labels and/or synonyms
      description: Vocabulary that can be used to refer to the concept instead of the preferred label. Alternative labels should be used to indicate community- or context-specific labels, abbreviations, shorthand forms and the like. You can also indicate synonymy (e.g. broad, exact, narrow, or related).
      placeholder: ex. sequencing platform company name
    validations:
      required: false
  - type: textarea
    id: additional-comments
    attributes:
      label: Additional Comments (not an annotation)
      description: Other information or context you would like the curator(s) to know.
      placeholder: 
      value: 
    validations:
      required: false
  - type: input
    id: contributor
    attributes: 
      label: Optional - Contributor Attribution
      description: Your contributor information (ORCiD preferred) to add the term, within the ontology, if change(s) are accepted.
      placeholder: 0000-0002-1825-0097 or https://orcid.org/0000-0002-1825-0097
    validations:
      required: false
